export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const OPERATION_LOG_REPOSITORY = Symbol('OPERATION_LOG_REPOSITORY');
export const SETTINGS_REPOSITORY = Symbol('SETTINGS_REPOSITORY');
export const AUTH_SERVICE = Symbol('AUTH_SERVICE');
export const USERS_SERVICE = Symbol('USERS_SERVICE');
export const SETTINGS_SERVICE = Symbol('SETTINGS_SERVICE');
export const PREPARATION_CONFIRMATION_SERVICE = Symbol('PREPARATION_CONFIRMATION_SERVICE');
